### ISSUE TITLE
extend keyword for interfaces / better example needed

### ISSUE THREAD

**Issue by evdama** [rmolinamir/typescript-cheatsheet#5]
example code at https://github.com/rmolinamir/typescript-cheatsheet#extends-keyword-interface-inheritance shows how to extend interfaces but then using `age` in this example kinda doesn't go to the core of what's needed to communicate there; it's not about `age` vs `age?`, it's about composition such as shown in the original example on https://www.typescriptlang.org/docs/handbook/interfaces.html --> Extending Interfaces

```
interface Shape {
    color: string;
}

interface Square extends Shape {
    sideLength: number;
}

let square = <Square>{};
square.color = "blue";
square.sideLength = 10;
```
for example shows the core idea of using `extends` with interfaces.

**Comment by rmolinamir** [comment]
You're right! Let's add additional examples. That example was intended to showcase how properties of the same keys could take priorities over others, but I'll add a similar example to the one from TypeScript official docs! Another nice catch 👍 

PS: I've added a new branch rule, so that changes must go through PR's in the future, just in case! This way we'll be able to review them and such.

**Comment by evdama** [comment]
closing, left some comments on the PR
